### ISSUE TITLE
ユーザー登録申請完了画面を作る

### ISSUE THREAD

**Issue by oyaoyaoyana** [SugiKent/make_friends_rikkyo#1]
## 概要
ユーザー登録申請後に表示される"少々お待ち下さいページ"を作成する

**Comment by oyaoyaoyana** [comment]
カウントダウン的にする？
24時間のカウントダウンで、それ以内に申請が降りないとNG

**Comment by oyaoyaoyana** [comment]
ユーザーで個別なものにできないのか

**Comment by oyaoyaoyana** [comment]
それか、合格発表的な感じにするとか

**Comment by SugiKent** [comment]
ページ自体は、最大20秒くらい表示しよう。
20秒したらusers/indexに遷移

んで、申請が許可された段階で公式垢からリプ形式で送られるというのは？（これはまた別issue）

### Thanksページデザイン
その人の投稿の前に何人の申請待ちがいるのか表示しよ。これは小さくてok.
なんかわくわくする。
「あなたの前に999人の申請待ちがいます。」

```
# user.rb
scope: unpublished => {where(published: false)}

# users_controller.rb
@users_count = User.unpublished.count
```

こんな感じかなぁ。

**Comment by SugiKent** [comment]
あ、ここにはやっぱりツイートボタン欲しいなぁ。

**Comment by SugiKent** [comment]
デザインはやるからさ、@users_countとその時登録されたuserのインスタンスだけ（@user）そのアクションに渡しといてー
