### ISSUE TITLE
twitter_idにバリデーションを追加

### ISSUE THREAD

**Issue by SugiKent** [SugiKent/make_friends_rikkyo#14]
## 概要
twitter_idのバリデーションを追加する。

## 詳細
- 「@」はいらない
- 登録画面ではすでに@が出力されており、「@」が不必要であることを伝える
- @で始まるものは無効とする
- 英数字と幾つかの記号（twitter本家のバリデーションを調査）のみ

**Comment by oyaoyaoyana** [comment]
選別方法
1,文字列の先頭に@があるかどうか？
ある→＠を消してください。表示
無し→２に進む

2,idのurlが存在するかどうか？で検証
"https://twitter.com/<%= user.twitter_id %>"にアクセス、具体的には下の【】内。
ある→クリア（３？）
無し→idが存在しません。表示

【http://piko.hateblo.jp/entry/2013/05/24/194739
これ使って、urlが存在するかどうか？で検証する】

３,twitterのbioグラフに春から立教があるかチェック
スクレイピングで
ProfileHeaderCard-bio u-dir
を取ってきて、正規表現で”春から立教”を確認true/ falseで返す。
ある→クリア
無し→？
【問題点】
エラーを返してしまうと、誰でも"春から立教を入れると通ってしまう"

**Comment by SugiKent** [comment]
1と2で。

その他オペレーション簡略化のために登録時の動作を増やす場合は別issue立ててー
