### ISSUE TITLE
利用規約ページ

### ISSUE THREAD

**Issue by SugiKent** [SugiKent/make_friends_rikkyo#16]
## 概要
利用規約ページを作成する。

## 詳細
個人情報を扱う面もあるので、ちゃんと作る。
同時にユーザー登録ページで、
```
利用規約に同意して、
『登録する』
```
という文言（リンク）も追加する。

**Comment by SugiKent** [comment]
今途中なのかもしれないけど、
users/newで利用規約へのリンク貼るだけでいいよ！

[利用規約]()に同意して
**登録する**

みたいな。

**Comment by oyaoyaoyana** [comment]
ok!

**Comment by SugiKent** [comment]
利用規約のページには前のtopに戻るリンクだけ追加してくださーい。
利用規約ページにはtopから遷移する（すでにリンクだけ設置済み）から、routingとviewとcontrollerなど（他のviewはあげない）だけでok!
