### ISSUE TITLE
入学式を一緒に行く友達が欲しかった

### ISSUE THREAD

**Issue by oyaoyaoyana** [SugiKent/make_friends_rikkyo#31]
# What 
入学式を一緒に行く友達をマッチ出来るような機能(期間限定で開放)

**Comment by oyaoyaoyana** [comment]
学部、学科でソート。
趣味でソート。

**Comment by oyaoyaoyana** [comment]
懸念点
・NOTシンプル

**Comment by SugiKent** [comment]
確かにこの欲望は大きそう。
何かフラグつけるかなー。
「入学式私ぼっちなので助けてくださいフラグ」 ww

ちなみにフラグって今でいうpublishedみたいなtrue or falseで登録されるカラムのことね！

**Comment by SugiKent** [comment]
あーー
シンプルを捨ててTwitterログイン機能とかつければいろんな機能追加できるんだよなーww
