### ISSUE TITLE
学科ごとの部屋を作る。

### ISSUE THREAD

**Issue by SugiKent** [SugiKent/make_friends_rikkyo#75]
## 概要
その学科生しか入れないページ
軽い自己紹介が出来る。

## なぜか
ユーザーが学科LINEに入りたがるように、同じ学科のつながりを求める。
しかし学科LINEに入りづらい(存在を知らないor誰に頼めば良いかわからない)

俺たちからしても、ここの利用が増えれば、ユーザーは「ここでとりあえず自己紹介しなくちゃ！」という焦りを与えて、ユーザー増加につながる

**Comment by oyaoyaoyana** [comment]
よきかな

**Comment by SugiKent** [comment]
@oyaoyaoya 
#77 ←こっちよりも学科の掲示板を先に開発して、まずは小さなコミュニティで使ってもらおうか。
その方が、
* 自己紹介の場と、「使い方」が明確
* ユーザーからすれば「必要性」がある。

と言う理由で使ってもらえる気がする。

**Comment by oyaoyaoyana** [comment]
おっけー

**Comment by SugiKent** [comment]
## DB設計
* Threadテーブル
* ThreadContentテーブル

## Threadテーブル
* id
* title
* description
* user_id（作成者）
* belong_type（紐づく種類[学科・サークルなど]）
* belong_id（紐づくid）
* published

## ThreadContentテーブル
* content
* user_id
* thread_id
* created_at（デフォルトである。並べるのに使う。）

**Comment by oyaoyaoyana** [comment]
belong_type（紐づく種類[学科・サークルなど]）
→データ型って何？
belong_id（紐づくid）
→何のidと紐づくの？

**Comment by oyaoyaoyana** [comment]
ThreadContentテーブル
・thread_idって必要だっけ？

**Comment by SugiKent** [comment]
belong_type（紐づく種類[学科・サークルなど]）
→データ型って何？
= string
belong_id（紐づくid）
→何のidと紐づくの？
= belong_typeによる。
例えばbelong_type=circleで、belong_id=1なら、サークルのID=1のやつ。
belong_type=departmentで、belong_id=3なら、学科のID=3のやつ。

**Comment by SugiKent** [comment]
ThreadContentテーブル
・thread_idって必要だっけ？
= 必要だわ。追記します。

**Comment by oyaoyaoyana** [comment]
おっけい！！！！！！！！

**Comment by oyaoyaoyana** [comment]
# indexページ仕様

## 考える事
- [x] 目的
- [x] 内容
- [ ] デザイン


## 目的
**新入生が自己紹介をする部屋への入り口**
見つけて、入ってもらうまでを極める

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
## 内容
### 使いやすそうなUI
#### 部屋の探しやすさ。
  - 検索機能
 - 自分の学部学科が上に来る。@topics = Topic.where(faculty_id: current_user.faculty)

### 使いたくなるようなUI
#### 他の部屋の盛り上がり具合が分かる
  - 投稿数
  - 最終更新日
  - 人數
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
## デザイン
- 部屋の名前が分かりやすい
- 活発度が分かる
  - 星とか、卵→ひよこ→鶏てきな
https://gyazo.com/995edd9049aa12b31cc46a623c1eb712
ブロックのデザイン

# 全体で意識したいこと
## おまけ
LINEよりもカジュアル、気軽に挨拶出来る。趣味とかLINEのTOP画像以外に情報に膨らみを持たせる。

**Comment by SugiKent** [comment]
### メモ
newアクションの際に、インスタンスを作るときに、belong_typeでデフォルトでcircleを入れるのをやめる

**Comment by SugiKent** [comment]
メニューにそのユーザーの学科の部屋が出るようにしています。
