### ISSUE TITLE
学科ごとの部屋を作る。おやなブランチ

### ISSUE THREAD

**Issue by SugiKent** [SugiKent/make_friends_rikkyo#86]
## 概要
#75 
のおやなの作業用ブランチ

**Comment by oyaoyaoyana** [comment]
# 部屋ごとの色分け

## 概要

(例)
- 自己紹介 => 赤
- ご飯 => 黄色
- サークル => 青
- 授業 => 緑
- 雑談 => 紫
等 色分け要素を作る

[イメージ](http://skypech.com/)


## how
【現状】
topicテーブルには、belongでサークルを分けてる

【変更】
id管理とタグ管理で分ける。

- id管理
  部屋の色分け要素。enam?

- タグ管理
  サークルとか詳細情報

**Comment by oyaoyaoyana** [comment]
id
→topicテーブルのtypeカラム。
　topic作成時にプルダウンで指定してもらって、クラスに"topic-#{topic.type}"
     topicの番号によって色が変わる仕組み
タグ
→http://tomy2002.hatenablog.com/entry/2016/02/27/022532
